name: Chidindu Ogbonna
bio: 'A Programmer from Nigeria'
description: My thoughts on all things Software
external-image: false
picture: 'assets/images/profile.jpg'

# If you want to include your resume, set to true
# and specify source (external or local).
# resume: true
# resume-external: true
# resume-url: https://google.com/?q=my+resume

permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

url: https://chidonna.github.io
analytics-gooogle: 'UA-103666117-1'

twitter: chidonna_codes
github: chidonna
stackoverflow: users/5631950/bones97
medium: chidonna
email: pogbonna34@gmail.com

authors:
    chidonna:
        name: Chidindu Ogbonna
        bio: A Programmer from Nigeria
        external-image: false
        picture: 'assets/images/profile.jpg'
        twitter: chidonna_codes

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# paginate: 5
# paginate_path: "blog/:num/"

projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
# Display links for next and previous posts for the specified categories
# show next & prev links in blog post?
blog-nav-links: false
# post-advance-links: [blog]
show-author: true
animation: true

sass:
    sass_dir: _sass
    style: :compressed


gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://chidonna.github.io

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh, tasks, LICENSE, help.md]
