title:               Chidindu Ogbonna
tagline:             '  A Programmer from Nigeria'
description: '<img src="/public/avatar.png" style="width: 400px;"/>'
url:                 http://chidonna.github.io
baseurl: ""
paginate:            5
permalink: /:year/:title/   # permalink: /:title/
excerpt_separator: <!--more-->
destination: _site
google_analytics: UA-103666117-1
# disqus: 'disqus-shortname'

version:             3.5.1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

exclude:
  - index.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - help.md
  - CNAME



